-- Exam Guard: Supabase schema
-- Run this in Supabase SQL Editor on a NEW project.
-- The GitHub Pages client uses only the publishable/anon key.
-- NEVER expose the service_role key in browser code.

create extension if not exists pgcrypto;

-- ---------- Core tables ----------
create table if not exists public.students (
  id uuid primary key default gen_random_uuid(),
  student_no text not null unique,
  full_name text not null,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.exams (
  id uuid primary key default gen_random_uuid(),
  code text not null unique,
  title text not null,
  duration_minutes integer not null check (duration_minutes between 1 and 600),
  status text not null default 'draft' check (status in ('draft','published','closed')),
  start_at timestamptz,
  end_at timestamptz,
  archived boolean not null default false,
  archived_at timestamptz,
  created_at timestamptz not null default now()
);

-- Keep upgrades idempotent for projects created with an earlier schema.
alter table public.exams add column if not exists archived boolean not null default false;
alter table public.exams add column if not exists archived_at timestamptz;

create table if not exists public.questions (
  id uuid primary key default gen_random_uuid(),
  exam_id uuid not null references public.exams(id) on delete cascade,
  position integer not null,
  prompt text not null,
  question_type text not null default 'mcq' check (question_type in ('mcq','text')),
  choices jsonb,
  correct_answer text,
  points numeric(8,2) not null default 1,
  created_at timestamptz not null default now(),
  unique(exam_id, position)
);

create table if not exists public.attempts (
  id uuid primary key default gen_random_uuid(),
  attempt_token uuid not null unique default gen_random_uuid(),
  exam_id uuid not null references public.exams(id) on delete cascade,
  student_id uuid not null references public.students(id) on delete cascade,
  status text not null default 'active' check (status in ('active','submitted','expired')),
  started_at timestamptz not null default now(),
  submitted_at timestamptz,
  score numeric(10,2),
  max_score numeric(10,2),
  user_agent text,
  unique(exam_id, student_id)
);

create table if not exists public.responses (
  attempt_id uuid not null references public.attempts(id) on delete cascade,
  question_id uuid not null references public.questions(id) on delete cascade,
  answer text,
  saved_at timestamptz not null default now(),
  primary key(attempt_id, question_id)
);

create table if not exists public.proctor_events (
  id bigint generated by default as identity primary key,
  attempt_id uuid not null references public.attempts(id) on delete cascade,
  event_type text not null,
  details jsonb not null default '{}'::jsonb,
  occurred_at timestamptz not null default now()
);

create index if not exists proctor_events_attempt_time_idx
  on public.proctor_events(attempt_id, occurred_at desc);

-- ---------- Teacher/admin auth ----------
create table if not exists public.exam_admins (
  user_id uuid primary key references auth.users(id) on delete cascade,
  is_admin boolean not null default false,
  created_at timestamptz not null default now()
);

create or replace function public.exam_guard_handle_new_auth_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.exam_admins(user_id) values (new.id)
  on conflict (user_id) do nothing;
  return new;
end;
$$;

drop trigger if exists exam_guard_on_auth_user_created on auth.users;
create trigger exam_guard_on_auth_user_created
after insert on auth.users
for each row execute function public.exam_guard_handle_new_auth_user();

create or replace function public.exam_guard_current_user_is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists(
    select 1 from public.exam_admins
    where user_id = auth.uid() and is_admin = true
  );
$$;

-- ---------- Lock down direct table access ----------
alter table public.students enable row level security;
alter table public.exams enable row level security;
alter table public.questions enable row level security;
alter table public.attempts enable row level security;
alter table public.responses enable row level security;
alter table public.proctor_events enable row level security;
alter table public.exam_admins enable row level security;

-- No anonymous table policies: students interact through controlled RPC functions only.

drop policy if exists admin_students on public.students;
create policy admin_students on public.students
for all to authenticated
using (public.exam_guard_current_user_is_admin())
with check (public.exam_guard_current_user_is_admin());

drop policy if exists admin_exams on public.exams;
create policy admin_exams on public.exams
for all to authenticated
using (public.exam_guard_current_user_is_admin())
with check (public.exam_guard_current_user_is_admin());

drop policy if exists admin_questions on public.questions;
create policy admin_questions on public.questions
for all to authenticated
using (public.exam_guard_current_user_is_admin())
with check (public.exam_guard_current_user_is_admin());

drop policy if exists admin_attempts on public.attempts;
create policy admin_attempts on public.attempts
for select to authenticated
using (public.exam_guard_current_user_is_admin());

drop policy if exists admin_attempts_delete on public.attempts;
create policy admin_attempts_delete on public.attempts
for delete to authenticated
using (public.exam_guard_current_user_is_admin());

drop policy if exists admin_responses on public.responses;
create policy admin_responses on public.responses
for select to authenticated
using (public.exam_guard_current_user_is_admin());

drop policy if exists admin_events on public.proctor_events;
create policy admin_events on public.proctor_events
for select to authenticated
using (public.exam_guard_current_user_is_admin());

drop policy if exists own_exam_admin on public.exam_admins;
create policy own_exam_admin on public.exam_admins
for select to authenticated
using (user_id = auth.uid());


-- Normalize student identifiers for tolerant matching.
create or replace function public.exam_guard_normalize_student_no(p_value text)
returns text
language sql
immutable
as $
  select regexp_replace(lower(coalesce(p_value,'')), '[^a-z0-9]', '', 'g');
$;

create or replace function public.exam_guard_normalize_name(p_value text)
returns text
language sql
immutable
as $
  select regexp_replace(lower(coalesce(p_value,'')), '[^a-z0-9]', '', 'g');
$;

-- ---------- Student RPC API ----------
create or replace function public.start_exam(
  p_exam_code text,
  p_student_no text,
  p_student_name text,
  p_user_agent text default null
)
returns table(
  attempt_token uuid,
  exam_title text,
  student_name text,
  student_no text,
  started_at timestamptz,
  ends_at timestamptz
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_exam public.exams%rowtype;
  v_student public.students%rowtype;
  v_attempt public.attempts%rowtype;
begin
  select * into v_exam
  from public.exams
  where lower(code) = lower(trim(p_exam_code))
    and status = 'published'
    and coalesce(archived, false) = false;

  if not found then
    raise exception 'Exam code is invalid or the exam is not published.';
  end if;

  if v_exam.start_at is not null and now() < v_exam.start_at then
    raise exception 'This exam has not opened yet.';
  end if;
  if v_exam.end_at is not null and now() > v_exam.end_at then
    raise exception 'This exam is already closed.';
  end if;

  select s.* into v_student
  from public.students as s
  where public.exam_guard_normalize_student_no(s.student_no)
        = public.exam_guard_normalize_student_no(p_student_no)
    and public.exam_guard_normalize_name(s.full_name)
        = public.exam_guard_normalize_name(p_student_name)
    and s.active = true;

  if not found then
    raise exception 'Student number and full name do not match an active student record.';
  end if;

  select * into v_attempt
  from public.attempts
  where exam_id = v_exam.id and student_id = v_student.id;

  if found then
    if v_attempt.status = 'submitted' then
      raise exception 'This student has already submitted this exam.';
    end if;
    if now() > v_attempt.started_at + make_interval(mins => v_exam.duration_minutes) then
      update public.attempts
      set status = 'expired'
      where id = v_attempt.id;
      raise exception 'The existing exam attempt has expired.';
    end if;
  else
    insert into public.attempts(exam_id, student_id, user_agent)
    values(v_exam.id, v_student.id, left(p_user_agent, 2000))
    returning * into v_attempt;
  end if;

  return query
  select
    v_attempt.attempt_token,
    v_exam.title,
    v_student.full_name,
    v_student.student_no,
    v_attempt.started_at,
    least(
      v_attempt.started_at + make_interval(mins => v_exam.duration_minutes),
      coalesce(v_exam.end_at, 'infinity'::timestamptz)
    );
end;
$$;

create or replace function public.get_exam_questions(p_attempt_token uuid)
returns table(
  question_id uuid,
  "position" integer,
  prompt text,
  question_type text,
  choices jsonb,
  points numeric
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_attempt public.attempts%rowtype;
  v_exam public.exams%rowtype;
begin
  select * into v_attempt from public.attempts where attempt_token = p_attempt_token;
  if not found or v_attempt.status <> 'active' then
    raise exception 'Invalid or inactive exam attempt.';
  end if;

  select * into v_exam from public.exams where id = v_attempt.exam_id;
  if now() > v_attempt.started_at + make_interval(mins => v_exam.duration_minutes) then
    update public.attempts set status = 'expired' where id = v_attempt.id;
    raise exception 'Exam time has expired.';
  end if;

  return query
  select q.id, q.position, q.prompt, q.question_type, q.choices, q.points
  from public.questions q
  where q.exam_id = v_attempt.exam_id
  order by q.position;
end;
$$;

create or replace function public.save_exam_response(
  p_attempt_token uuid,
  p_question_id uuid,
  p_answer text
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_attempt public.attempts%rowtype;
  v_exam public.exams%rowtype;
begin
  select * into v_attempt from public.attempts where attempt_token = p_attempt_token;
  if not found or v_attempt.status <> 'active' then
    raise exception 'Invalid or inactive exam attempt.';
  end if;

  select * into v_exam from public.exams where id = v_attempt.exam_id;
  if now() > v_attempt.started_at + make_interval(mins => v_exam.duration_minutes) then
    update public.attempts set status = 'expired' where id = v_attempt.id;
    raise exception 'Exam time has expired.';
  end if;

  if not exists(
    select 1 from public.questions
    where id = p_question_id and exam_id = v_attempt.exam_id
  ) then
    raise exception 'Question does not belong to this exam.';
  end if;

  insert into public.responses(attempt_id, question_id, answer, saved_at)
  values(v_attempt.id, p_question_id, left(p_answer, 20000), now())
  on conflict(attempt_id, question_id)
  do update set answer = excluded.answer, saved_at = now();
end;
$$;

create or replace function public.log_proctor_event(
  p_attempt_token uuid,
  p_event_type text,
  p_details jsonb default '{}'::jsonb
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_attempt_id uuid;
begin
  select id into v_attempt_id
  from public.attempts
  where attempt_token = p_attempt_token
    and status = 'active';

  if v_attempt_id is null then
    return;
  end if;

  insert into public.proctor_events(attempt_id, event_type, details)
  values(
    v_attempt_id,
    left(coalesce(p_event_type,'unknown'), 100),
    coalesce(p_details, '{}'::jsonb)
  );
end;
$$;

create or replace function public.submit_exam(p_attempt_token uuid)
returns table(score numeric, max_score numeric)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_attempt public.attempts%rowtype;
  v_score numeric;
  v_max numeric;
begin
  select * into v_attempt
  from public.attempts
  where attempt_token = p_attempt_token;

  if not found then
    raise exception 'Invalid exam attempt.';
  end if;

  if v_attempt.status = 'submitted' then
    return query select v_attempt.score, v_attempt.max_score;
    return;
  end if;

  -- Auto-score questions that have a correct_answer. Text/manual questions may leave it null.
  select
    coalesce(sum(
      case
        when q.correct_answer is not null
         and lower(trim(coalesce(r.answer,''))) = lower(trim(q.correct_answer))
        then q.points else 0
      end
    ),0),
    coalesce(sum(case when q.correct_answer is not null then q.points else 0 end),0)
  into v_score, v_max
  from public.questions q
  left join public.responses r
    on r.question_id = q.id and r.attempt_id = v_attempt.id
  where q.exam_id = v_attempt.exam_id;

  update public.attempts
  set status = 'submitted',
      submitted_at = now(),
      score = v_score,
      max_score = v_max
  where id = v_attempt.id;

  insert into public.proctor_events(attempt_id, event_type, details)
  values(v_attempt.id, 'exam_submitted', jsonb_build_object('score',v_score,'max_score',v_max));

  return query select v_score, v_max;
end;
$$;



-- ---------- Admin maintenance RPCs ----------
create or replace function public.admin_delete_attempt(p_attempt_id uuid)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  v_deleted integer := 0;
begin
  if auth.uid() is null or not public.exam_guard_current_user_is_admin() then
    raise exception 'Administrator access required.';
  end if;

  delete from public.attempts
  where id = p_attempt_id;

  get diagnostics v_deleted = row_count;
  return v_deleted = 1;
end;
$$;

create or replace function public.admin_delete_exam(p_exam_id uuid)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  v_deleted integer := 0;
begin
  if auth.uid() is null or not public.exam_guard_current_user_is_admin() then
    raise exception 'Administrator access required.';
  end if;

  delete from public.exams
  where id = p_exam_id;

  get diagnostics v_deleted = row_count;
  return v_deleted = 1;
end;
$$;

revoke all on function public.admin_delete_attempt(uuid) from public;
revoke all on function public.admin_delete_exam(uuid) from public;
grant execute on function public.admin_delete_attempt(uuid) to authenticated;
grant execute on function public.admin_delete_exam(uuid) to authenticated;

-- Restrict execution explicitly.
revoke all on function public.start_exam(text,text,text,text) from public;
revoke all on function public.get_exam_questions(uuid) from public;
revoke all on function public.save_exam_response(uuid,uuid,text) from public;
revoke all on function public.log_proctor_event(uuid,text,jsonb) from public;
revoke all on function public.submit_exam(uuid) from public;

grant execute on function public.start_exam(text,text,text,text) to anon, authenticated;
grant execute on function public.get_exam_questions(uuid) to anon, authenticated;
grant execute on function public.save_exam_response(uuid,uuid,text) to anon, authenticated;
grant execute on function public.log_proctor_event(uuid,text,jsonb) to anon, authenticated;
grant execute on function public.submit_exam(uuid) to anon, authenticated;

-- Admin table reads/writes are still controlled by RLS.
grant select, insert, update, delete on public.students, public.exams, public.questions to authenticated;
grant select, delete on public.attempts to authenticated;
grant select on public.responses, public.proctor_events, public.exam_admins to authenticated;

-- ---------- Example seed data ----------
-- Replace these with your real students/exam.
insert into public.students(student_no, full_name)
values
  ('2026-0001','Sample Student One'),
  ('2026-0002','Sample Student Two')
on conflict (student_no) do nothing;

insert into public.exams(code,title,duration_minutes,status)
values ('DEMO-EXAM','Demo Examination',30,'published')
on conflict (code) do nothing;

insert into public.questions(exam_id,position,prompt,question_type,choices,correct_answer,points)
select e.id, 1, 'What is 2 + 2?', 'mcq',
       '["3","4","5","6"]'::jsonb, '4', 1
from public.exams e
where e.code='DEMO-EXAM'
on conflict (exam_id,position) do nothing;

insert into public.questions(exam_id,position,prompt,question_type,choices,correct_answer,points)
select e.id, 2, 'Which number is prime?', 'mcq',
       '["9","15","17","21"]'::jsonb, '17', 1
from public.exams e
where e.code='DEMO-EXAM'
on conflict (exam_id,position) do nothing;

-- IMPORTANT: after creating a teacher in Supabase Authentication > Users,
-- make that account an admin by running:
--
-- update public.exam_admins
-- set is_admin = true
-- where user_id = 'PASTE-TEACHER-AUTH-USER-UUID-HERE';
