-- Exam Guard: Supabase schema
-- Run this in Supabase SQL Editor on a NEW project.
-- The GitHub Pages client uses only the publishable/anon key.
-- NEVER expose the service_role key in browser code.

create extension if not exists pgcrypto;

-- ---------- Core tables ----------
create table if not exists public.students (
  id uuid primary key default gen_random_uuid(),
  student_no text not null unique,
  full_name text not null,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.exams (
  id uuid primary key default gen_random_uuid(),
  code text not null unique,
  title text not null,
  duration_minutes integer not null check (duration_minutes between 1 and 600),
  status text not null default 'draft' check (status in ('draft','published','closed')),
  start_at timestamptz,
  end_at timestamptz,
  archived boolean not null default false,
  archived_at timestamptz,
  created_at timestamptz not null default now()
);

-- Keep upgrades idempotent for projects created with an earlier schema.
alter table public.exams add column if not exists archived boolean not null default false;
alter table public.exams add column if not exists archived_at timestamptz;

create table if not exists public.questions (
  id uuid primary key default gen_random_uuid(),
  exam_id uuid not null references public.exams(id) on delete cascade,
  position integer not null,
  prompt text not null,
  question_type text not null default 'mcq' check (question_type in ('mcq','text')),
  choices jsonb,
  correct_answer text,
  points numeric(8,2) not null default 1,
  created_at timestamptz not null default now(),
  unique(exam_id, position)
);

create table if not exists public.attempts (
  id uuid primary key default gen_random_uuid(),
  attempt_token uuid not null unique default gen_random_uuid(),
  exam_id uuid not null references public.exams(id) on delete cascade,
  student_id uuid not null references public.students(id) on delete cascade,
  status text not null default 'active' check (status in ('active','submitted','expired')),
  started_at timestamptz not null default now(),
  submitted_at timestamptz,
  score numeric(10,2),
  max_score numeric(10,2),
  user_agent text,
  unique(exam_id, student_id)
);

create table if not exists public.responses (
  attempt_id uuid not null references public.attempts(id) on delete cascade,
  question_id uuid not null references public.questions(id) on delete cascade,
  answer text,
  saved_at timestamptz not null default now(),
  primary key(attempt_id, question_id)
);

create table if not exists public.proctor_events (
  id bigint generated by default as identity primary key,
  attempt_id uuid not null references public.attempts(id) on delete cascade,
  event_type text not null,
  details jsonb not null default '{}'::jsonb,
  occurred_at timestamptz not null default now()
);

create index if not exists proctor_events_attempt_time_idx
  on public.proctor_events(attempt_id, occurred_at desc);

-- ---------- Teacher/admin auth ----------
create table if not exists public.exam_admins (
  user_id uuid primary key references auth.users(id) on delete cascade,
  is_admin boolean not null default false,
  created_at timestamptz not null default now()
);

create or replace function public.exam_guard_handle_new_auth_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.exam_admins(user_id) values (new.id)
  on conflict (user_id) do nothing;
  return new;
end;
$$;

drop trigger if exists exam_guard_on_auth_user_created on auth.users;
create trigger exam_guard_on_auth_user_created
after insert on auth.users
for each row execute function public.exam_guard_handle_new_auth_user();

create or replace function public.exam_guard_current_user_is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists(
    select 1 from public.exam_admins
    where user_id = auth.uid() and is_admin = true
  );
$$;

-- ---------- Lock down direct table access ----------
alter table public.students enable row level security;
alter table public.exams enable row level security;
alter table public.questions enable row level security;
alter table public.attempts enable row level security;
alter table public.responses enable row level security;
alter table public.proctor_events enable row level security;
alter table public.exam_admins enable row level security;

-- No anonymous table policies: students interact through controlled RPC functions only.

drop policy if exists admin_students on public.students;
create policy admin_students on public.students
for all to authenticated
using (public.exam_guard_current_user_is_admin())
with check (public.exam_guard_current_user_is_admin());

drop policy if exists admin_exams on public.exams;
create policy admin_exams on public.exams
for all to authenticated
using (public.exam_guard_current_user_is_admin())
with check (public.exam_guard_current_user_is_admin());

drop policy if exists admin_questions on public.questions;
create policy admin_questions on public.questions
for all to authenticated
using (public.exam_guard_current_user_is_admin())
with check (public.exam_guard_current_user_is_admin());

drop policy if exists admin_attempts on public.attempts;
create policy admin_attempts on public.attempts
for select to authenticated
using (public.exam_guard_current_user_is_admin());

drop policy if exists admin_attempts_delete on public.attempts;
create policy admin_attempts_delete on public.attempts
for delete to authenticated
using (public.exam_guard_current_user_is_admin());

drop policy if exists admin_responses on public.responses;
create policy admin_responses on public.responses
for select to authenticated
using (public.exam_guard_current_user_is_admin());

drop policy if exists admin_events on public.proctor_events;
create policy admin_events on public.proctor_events
for select to authenticated
using (public.exam_guard_current_user_is_admin());

drop policy if exists own_exam_admin on public.exam_admins;
create policy own_exam_admin on public.exam_admins
for select to authenticated
using (user_id = auth.uid());


-- Normalize student identifiers for tolerant matching.
create or replace function public.exam_guard_normalize_student_no(p_value text)
returns text
language sql
immutable
as $norm$
  select regexp_replace(lower(coalesce(p_value,'')), '[^a-z0-9]', '', 'g');
$norm$;

create or replace function public.exam_guard_normalize_name(p_value text)
returns text
language sql
immutable
as $norm$
  select regexp_replace(lower(coalesce(p_value,'')), '[^a-z0-9]', '', 'g');
$norm$;


-- ---------- Student identity preview before exam start ----------
create or replace function public.preview_exam_identity(
  p_exam_code text,
  p_student_no text
)
returns table(
  exam_title text,
  student_name text,
  student_no text
)
language plpgsql
security definer
set search_path = public
as $identity$
declare
  v_exam public.exams%rowtype;
  v_student public.students%rowtype;
begin
  select * into v_exam
  from public.exams
  where lower(code) = lower(trim(p_exam_code))
    and status = 'published'
    and coalesce(archived, false) = false;

  if not found then
    raise exception 'Exam code is invalid or the exam is not published.';
  end if;

  if v_exam.start_at is not null and now() < v_exam.start_at then
    raise exception 'This exam has not opened yet.';
  end if;

  if v_exam.end_at is not null and now() > v_exam.end_at then
    raise exception 'This exam is already closed.';
  end if;

  select s.* into v_student
  from public.students s
  where public.exam_guard_normalize_student_no(s.student_no)
        = public.exam_guard_normalize_student_no(p_student_no)
    and s.active = true
  limit 1;

  if not found then
    raise exception 'Student ID does not match an active student record.';
  end if;

  return query
  select v_exam.title, v_student.full_name, v_student.student_no;
end;
$identity$;

revoke all on function public.preview_exam_identity(text,text) from public;
grant execute on function public.preview_exam_identity(text,text) to anon, authenticated;

-- ---------- Student RPC API ----------
create or replace function public.start_exam(
  p_exam_code text,
  p_student_no text,
  p_user_agent text default null
)
returns table(
  attempt_token uuid,
  exam_title text,
  student_name text,
  student_no text,
  started_at timestamptz,
  ends_at timestamptz
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_exam public.exams%rowtype;
  v_student public.students%rowtype;
  v_attempt public.attempts%rowtype;
begin
  select * into v_exam
  from public.exams
  where lower(code) = lower(trim(p_exam_code))
    and status = 'published'
    and coalesce(archived, false) = false;

  if not found then
    raise exception 'Exam code is invalid or the exam is not published.';
  end if;

  if v_exam.start_at is not null and now() < v_exam.start_at then
    raise exception 'This exam has not opened yet.';
  end if;

  if v_exam.end_at is not null and now() > v_exam.end_at then
    raise exception 'This exam is already closed.';
  end if;

  select s.* into v_student
  from public.students as s
  where public.exam_guard_normalize_student_no(s.student_no)
        = public.exam_guard_normalize_student_no(p_student_no)
    and s.active = true;

  if not found then
    raise exception 'Student ID does not match an active student record.';
  end if;

  select * into v_attempt
  from public.attempts
  where exam_id = v_exam.id and student_id = v_student.id;

  if found then
    if v_attempt.status = 'submitted' then
      raise exception 'This student has already submitted this exam.';
    end if;

    if now() > v_attempt.started_at + make_interval(mins => v_exam.duration_minutes) then
      update public.attempts
      set status = 'expired'
      where id = v_attempt.id;
      raise exception 'The existing exam attempt has expired.';
    end if;
  else
    insert into public.attempts(exam_id, student_id, user_agent)
    values(v_exam.id, v_student.id, left(p_user_agent, 2000))
    returning * into v_attempt;
  end if;

  return query
  select
    v_attempt.attempt_token,
    v_exam.title,
    v_student.full_name,
    v_student.student_no,
    v_attempt.started_at,
    least(
      v_attempt.started_at + make_interval(mins => v_exam.duration_minutes),
      coalesce(v_exam.end_at, 'infinity'::timestamptz)
    );
end;
$$;


-- ---------- Active attempt recovery ----------
create or replace function public.resume_exam(p_attempt_token uuid)
returns table(
  attempt_token uuid,
  exam_title text,
  student_name text,
  student_no text,
  started_at timestamptz,
  ends_at timestamptz
)
language plpgsql
security definer
set search_path = public
as $resume$
declare
  v_attempt public.attempts%rowtype;
  v_exam public.exams%rowtype;
  v_student public.students%rowtype;
  v_ends_at timestamptz;
begin
  select * into v_attempt
  from public.attempts
  where attempts.attempt_token = p_attempt_token;

  if not found or v_attempt.status <> 'active' then
    raise exception 'No active exam session was found.';
  end if;

  select * into v_exam from public.exams where id = v_attempt.exam_id;
  select * into v_student from public.students where id = v_attempt.student_id;

  v_ends_at := least(
    v_attempt.started_at + make_interval(mins => v_exam.duration_minutes),
    coalesce(v_exam.end_at, 'infinity'::timestamptz)
  );

  if now() > v_ends_at then
    update public.attempts
    set status = 'expired'
    where id = v_attempt.id;

    raise exception 'The saved exam session has expired.';
  end if;

  return query
  select
    v_attempt.attempt_token,
    v_exam.title,
    v_student.full_name,
    v_student.student_no,
    v_attempt.started_at,
    v_ends_at;
end;
$resume$;

create or replace function public.get_saved_exam_responses(p_attempt_token uuid)
returns table(
  question_id uuid,
  answer text,
  saved_at timestamptz
)
language plpgsql
security definer
set search_path = public
as $resume$
declare
  v_attempt public.attempts%rowtype;
  v_exam public.exams%rowtype;
begin
  select * into v_attempt
  from public.attempts
  where attempts.attempt_token = p_attempt_token;

  if not found or v_attempt.status <> 'active' then
    raise exception 'No active exam session was found.';
  end if;

  select * into v_exam from public.exams where id = v_attempt.exam_id;

  if now() > least(
    v_attempt.started_at + make_interval(mins => v_exam.duration_minutes),
    coalesce(v_exam.end_at, 'infinity'::timestamptz)
  ) then
    update public.attempts
    set status = 'expired'
    where id = v_attempt.id;

    raise exception 'The saved exam session has expired.';
  end if;

  return query
  select r.question_id, r.answer, r.saved_at
  from public.responses r
  where r.attempt_id = v_attempt.id
  order by r.saved_at;
end;
$resume$;

revoke all on function public.resume_exam(uuid) from public;
revoke all on function public.get_saved_exam_responses(uuid) from public;
grant execute on function public.resume_exam(uuid) to anon, authenticated;
grant execute on function public.get_saved_exam_responses(uuid) to anon, authenticated;

create or replace function public.get_exam_questions(p_attempt_token uuid)
returns table(
  question_id uuid,
  "position" integer,
  prompt text,
  question_type text,
  choices jsonb,
  points numeric
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_attempt public.attempts%rowtype;
  v_exam public.exams%rowtype;
begin
  select * into v_attempt from public.attempts where attempt_token = p_attempt_token;
  if not found or v_attempt.status <> 'active' then
    raise exception 'Invalid or inactive exam attempt.';
  end if;

  select * into v_exam from public.exams where id = v_attempt.exam_id;
  if now() > v_attempt.started_at + make_interval(mins => v_exam.duration_minutes) then
    update public.attempts set status = 'expired' where id = v_attempt.id;
    raise exception 'Exam time has expired.';
  end if;

  return query
  select q.id, q.position, q.prompt, q.question_type, q.choices, q.points
  from public.questions q
  where q.exam_id = v_attempt.exam_id
  order by q.position;
end;
$$;

create or replace function public.save_exam_response(
  p_attempt_token uuid,
  p_question_id uuid,
  p_answer text
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_attempt public.attempts%rowtype;
  v_exam public.exams%rowtype;
begin
  select * into v_attempt from public.attempts where attempt_token = p_attempt_token;
  if not found or v_attempt.status <> 'active' then
    raise exception 'Invalid or inactive exam attempt.';
  end if;

  select * into v_exam from public.exams where id = v_attempt.exam_id;
  if now() > v_attempt.started_at + make_interval(mins => v_exam.duration_minutes) then
    update public.attempts set status = 'expired' where id = v_attempt.id;
    raise exception 'Exam time has expired.';
  end if;

  if not exists(
    select 1 from public.questions
    where id = p_question_id and exam_id = v_attempt.exam_id
  ) then
    raise exception 'Question does not belong to this exam.';
  end if;

  insert into public.responses(attempt_id, question_id, answer, saved_at)
  values(v_attempt.id, p_question_id, left(p_answer, 20000), now())
  on conflict(attempt_id, question_id)
  do update set answer = excluded.answer, saved_at = now();
end;
$$;

create or replace function public.log_proctor_event(
  p_attempt_token uuid,
  p_event_type text,
  p_details jsonb default '{}'::jsonb
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_attempt_id uuid;
begin
  select id into v_attempt_id
  from public.attempts
  where attempt_token = p_attempt_token
    and status = 'active';

  if v_attempt_id is null then
    return;
  end if;

  insert into public.proctor_events(attempt_id, event_type, details)
  values(
    v_attempt_id,
    left(coalesce(p_event_type,'unknown'), 100),
    coalesce(p_details, '{}'::jsonb)
  );
end;
$$;

create or replace function public.submit_exam(p_attempt_token uuid)
returns table(score numeric, max_score numeric)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_attempt public.attempts%rowtype;
  v_score numeric;
  v_max numeric;
begin
  select * into v_attempt
  from public.attempts
  where attempt_token = p_attempt_token;

  if not found then
    raise exception 'Invalid exam attempt.';
  end if;

  if v_attempt.status = 'submitted' then
    return query select v_attempt.score, v_attempt.max_score;
    return;
  end if;

  -- Auto-score questions that have a correct_answer. Text/manual questions may leave it null.
  select
    coalesce(sum(
      case
        when q.correct_answer is not null
         and lower(trim(coalesce(r.answer,''))) = lower(trim(q.correct_answer))
        then q.points else 0
      end
    ),0),
    coalesce(sum(case when q.correct_answer is not null then q.points else 0 end),0)
  into v_score, v_max
  from public.questions q
  left join public.responses r
    on r.question_id = q.id and r.attempt_id = v_attempt.id
  where q.exam_id = v_attempt.exam_id;

  update public.attempts
  set status = 'submitted',
      submitted_at = now(),
      score = v_score,
      max_score = v_max
  where id = v_attempt.id;

  insert into public.proctor_events(attempt_id, event_type, details)
  values(v_attempt.id, 'exam_submitted', jsonb_build_object('score',v_score,'max_score',v_max));

  return query select v_score, v_max;
end;
$$;




-- ---------- Submitted result report API ----------
create or replace function public.exam_guard_build_attempt_report(p_attempt_id uuid)
returns jsonb
language sql
stable
security definer
set search_path = public
as $report$
  select jsonb_build_object(
    'attempt_id', a.id,
    'student_name', s.full_name,
    'student_no', s.student_no,
    'exam_title', e.title,
    'exam_code', e.code,
    'teacher_name', coalesce(nullif(ea.display_name, ''), nullif(ea.email, ''), 'Teacher'),
    'started_at', a.started_at,
    'submitted_at', a.submitted_at,
    'score', a.score,
    'max_score', a.max_score,
    'percentage', case
      when coalesce(a.max_score, 0) > 0 then round((a.score / a.max_score) * 100, 2)
      else null
    end,
    'items', coalesce((
      select jsonb_agg(
        jsonb_build_object(
          'position', q.position,
          'prompt', q.prompt,
          'question_type', q.question_type,
          'student_answer', coalesce(r.answer, ''),
          'correct_answer', q.correct_answer,
          'points', q.points,
          'points_awarded', case
            when q.correct_answer is not null
             and lower(trim(coalesce(r.answer,''))) = lower(trim(q.correct_answer))
            then q.points
            when q.correct_answer is null then null
            else 0
          end,
          'result', case
            when q.correct_answer is null then 'manual'
            when lower(trim(coalesce(r.answer,''))) = lower(trim(q.correct_answer)) then 'correct'
            else 'wrong'
          end
        )
        order by q.position
      )
      from public.questions q
      left join public.responses r
        on r.question_id = q.id
       and r.attempt_id = a.id
      where q.exam_id = a.exam_id
    ), '[]'::jsonb)
  )
  from public.attempts a
  join public.students s on s.id = a.student_id
  join public.exams e on e.id = a.exam_id
  left join public.exam_admins ea on ea.user_id = e.owner_id
  where a.id = p_attempt_id
    and a.status = 'submitted';
$report$;

create or replace function public.get_submitted_exam_report(p_attempt_token uuid)
returns jsonb
language plpgsql
security definer
set search_path = public
as $report$
declare
  v_attempt_id uuid;
  v_report jsonb;
begin
  select id into v_attempt_id
  from public.attempts
  where attempt_token = p_attempt_token
    and status = 'submitted';

  if v_attempt_id is null then
    raise exception 'Submitted exam report is not available.';
  end if;

  v_report := public.exam_guard_build_attempt_report(v_attempt_id);
  if v_report is null then
    raise exception 'Submitted exam report is not available.';
  end if;

  return v_report;
end;
$report$;

create or replace function public.admin_get_attempt_report(p_attempt_id uuid)
returns jsonb
language plpgsql
security definer
set search_path = public
as $report$
declare
  v_report jsonb;
begin
  if auth.uid() is null or not public.exam_guard_current_user_is_admin() then
    raise exception 'Administrator access required.';
  end if;

  v_report := public.exam_guard_build_attempt_report(p_attempt_id);
  if v_report is null then
    raise exception 'Only submitted attempts have result reports.';
  end if;

  return v_report;
end;
$report$;

revoke all on function public.exam_guard_build_attempt_report(uuid) from public;
revoke all on function public.get_submitted_exam_report(uuid) from public;
revoke all on function public.admin_get_attempt_report(uuid) from public;

grant execute on function public.get_submitted_exam_report(uuid) to anon, authenticated;
grant execute on function public.admin_get_attempt_report(uuid) to authenticated;

-- ---------- Admin maintenance RPCs ----------
create or replace function public.admin_delete_attempt(p_attempt_id uuid)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  v_deleted integer := 0;
begin
  if auth.uid() is null or not public.exam_guard_current_user_is_admin() then
    raise exception 'Administrator access required.';
  end if;

  delete from public.attempts
  where id = p_attempt_id;

  get diagnostics v_deleted = row_count;
  return v_deleted = 1;
end;
$$;

create or replace function public.admin_delete_exam(p_exam_id uuid)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  v_deleted integer := 0;
begin
  if auth.uid() is null or not public.exam_guard_current_user_is_admin() then
    raise exception 'Administrator access required.';
  end if;

  delete from public.exams
  where id = p_exam_id;

  get diagnostics v_deleted = row_count;
  return v_deleted = 1;
end;
$$;

revoke all on function public.admin_delete_attempt(uuid) from public;
revoke all on function public.admin_delete_exam(uuid) from public;
grant execute on function public.admin_delete_attempt(uuid) to authenticated;
grant execute on function public.admin_delete_exam(uuid) to authenticated;

-- Restrict execution explicitly.
revoke all on function public.start_exam(text,text,text) from public;
revoke all on function public.get_exam_questions(uuid) from public;
revoke all on function public.save_exam_response(uuid,uuid,text) from public;
revoke all on function public.log_proctor_event(uuid,text,jsonb) from public;
revoke all on function public.submit_exam(uuid) from public;

grant execute on function public.start_exam(text,text,text) to anon, authenticated;
grant execute on function public.get_exam_questions(uuid) to anon, authenticated;
grant execute on function public.save_exam_response(uuid,uuid,text) to anon, authenticated;
grant execute on function public.log_proctor_event(uuid,text,jsonb) to anon, authenticated;
grant execute on function public.submit_exam(uuid) to anon, authenticated;

-- Admin table reads/writes are still controlled by RLS.
grant select, insert, update, delete on public.students, public.exams, public.questions to authenticated;
grant select, delete on public.attempts to authenticated;
grant select on public.responses, public.proctor_events, public.exam_admins to authenticated;

-- Front-camera proctoring photos with 24-hour retention.
-- Run once in Supabase SQL Editor.
-- Photos are stored in a PRIVATE Storage bucket.

create table if not exists public.proctor_photos (
  id uuid primary key default gen_random_uuid(),
  attempt_id uuid not null references public.attempts(id) on delete cascade,
  object_path text not null unique,
  captured_at timestamptz not null default now(),
  expires_at timestamptz not null default (now() + interval '24 hours'),
  created_at timestamptz not null default now()
);

create index if not exists proctor_photos_attempt_time_idx
  on public.proctor_photos(attempt_id, captured_at);

create index if not exists proctor_photos_expiry_idx
  on public.proctor_photos(expires_at);

alter table public.proctor_photos enable row level security;

drop policy if exists teacher_proctor_photos_select on public.proctor_photos;
create policy teacher_proctor_photos_select
on public.proctor_photos
for select
to authenticated
using (public.exam_guard_can_access_attempt(attempt_id));

-- Browser clients do not directly insert/delete photos.
-- Uploads and cleanup are performed by Edge Functions using a server-side admin key.

insert into storage.buckets (
  id,
  name,
  public,
  file_size_limit,
  allowed_mime_types
)
values (
  'exam-proctor-photos',
  'exam-proctor-photos',
  false,
  600000,
  array['image/jpeg']::text[]
)
on conflict (id) do update
set public = false,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

grant select on public.proctor_photos to authenticated;


-- ---------- Example seed data ----------
-- Replace these with your real students/exam.
insert into public.students(student_no, full_name)
values
  ('2026-0001','Sample Student One'),
  ('2026-0002','Sample Student Two')
on conflict (student_no) do nothing;

insert into public.exams(code,title,duration_minutes,status)
values ('DEMO-EXAM','Demo Examination',30,'published')
on conflict (code) do nothing;

insert into public.questions(exam_id,position,prompt,question_type,choices,correct_answer,points)
select e.id, 1, 'What is 2 + 2?', 'mcq',
       '["3","4","5","6"]'::jsonb, '4', 1
from public.exams e
where e.code='DEMO-EXAM'
on conflict (exam_id,position) do nothing;

insert into public.questions(exam_id,position,prompt,question_type,choices,correct_answer,points)
select e.id, 2, 'Which number is prime?', 'mcq',
       '["9","15","17","21"]'::jsonb, '17', 1
from public.exams e
where e.code='DEMO-EXAM'
on conflict (exam_id,position) do nothing;

-- IMPORTANT: after creating a teacher in Supabase Authentication > Users,
-- make that account an admin by running:
--
-- update public.exam_admins
-- set is_admin = true
-- where user_id = 'PASTE-TEACHER-AUTH-USER-UUID-HERE';


-- Multi-teacher ownership and Main Admin support mode.
-- Run ONCE in Supabase SQL Editor on the existing Exam Guard project.
-- Main Admin: sir.princejobetroh@gmail.com
-- Existing students remain shared by all authorized teachers.
-- Existing exams are assigned to the Main Admin.

-- 1. Extend teacher profiles.
alter table public.exam_admins
  add column if not exists email text,
  add column if not exists display_name text,
  add column if not exists role text not null default 'teacher';

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'exam_admins_role_check'
  ) then
    alter table public.exam_admins
      add constraint exam_admins_role_check
      check (role in ('main_admin','teacher'));
  end if;
end $$;

-- Backfill profile data from Supabase Auth.
update public.exam_admins ea
set email = coalesce(ea.email, u.email),
    display_name = coalesce(
      nullif(ea.display_name, ''),
      nullif(u.raw_user_meta_data->>'full_name', ''),
      split_part(coalesce(u.email,''), '@', 1)
    )
from auth.users u
where u.id = ea.user_id;

-- Make Sir Prince the Main Admin.
update public.exam_admins
set is_admin = true,
    role = 'main_admin',
    email = 'sir.princejobetroh@gmail.com',
    display_name = coalesce(nullif(display_name,''), 'Sir Prince Jobetroh N. Cabaya Cruz')
where lower(email) = 'sir.princejobetroh@gmail.com'
   or user_id in (
     select id from auth.users
     where lower(email) = 'sir.princejobetroh@gmail.com'
   );

-- Keep future Auth users mirrored into exam_admins.
create or replace function public.exam_guard_handle_new_auth_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $teacher$
begin
  insert into public.exam_admins(user_id, email, display_name, role, is_admin)
  values (
    new.id,
    new.email,
    coalesce(
      nullif(new.raw_user_meta_data->>'full_name',''),
      split_part(coalesce(new.email,''), '@', 1)
    ),
    case
      when lower(coalesce(new.email,'')) = 'sir.princejobetroh@gmail.com'
      then 'main_admin'
      else 'teacher'
    end,
    case
      when lower(coalesce(new.email,'')) = 'sir.princejobetroh@gmail.com'
      then true
      else false
    end
  )
  on conflict (user_id) do update
  set email = excluded.email,
      display_name = coalesce(public.exam_admins.display_name, excluded.display_name);

  return new;
end;
$teacher$;

-- 2. Give each exam an owner.
alter table public.exams
  add column if not exists owner_id uuid references auth.users(id) on delete restrict;

alter table public.exams
  alter column owner_id set default auth.uid();

-- Existing exams belong to the Main Admin.
update public.exams e
set owner_id = u.id
from auth.users u
where e.owner_id is null
  and lower(u.email) = 'sir.princejobetroh@gmail.com';

create index if not exists exams_owner_created_idx
  on public.exams(owner_id, created_at desc);

-- 3. Authorization helpers.
create or replace function public.exam_guard_current_user_is_main_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $auth$
  select exists(
    select 1
    from public.exam_admins
    where user_id = auth.uid()
      and is_admin = true
      and role = 'main_admin'
  );
$auth$;

create or replace function public.exam_guard_can_access_exam(p_exam_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $auth$
  select
    public.exam_guard_current_user_is_main_admin()
    or exists(
      select 1
      from public.exams e
      where e.id = p_exam_id
        and e.owner_id = auth.uid()
        and public.exam_guard_current_user_is_admin()
    );
$auth$;

create or replace function public.exam_guard_can_access_attempt(p_attempt_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $auth$
  select exists(
    select 1
    from public.attempts a
    where a.id = p_attempt_id
      and public.exam_guard_can_access_exam(a.exam_id)
  );
$auth$;

-- 4. Replace teacher/admin RLS policies.
-- Shared student roster: every authorized teacher uses the same Student IDs.
drop policy if exists admin_students on public.students;
create policy admin_students on public.students
for all to authenticated
using (public.exam_guard_current_user_is_admin())
with check (public.exam_guard_current_user_is_admin());

-- Exams: regular teachers only their own; Main Admin all teachers.
drop policy if exists admin_exams on public.exams;
create policy admin_exams on public.exams
for select to authenticated
using (
  public.exam_guard_current_user_is_main_admin()
  or (
    public.exam_guard_current_user_is_admin()
    and owner_id = auth.uid()
  )
);

drop policy if exists teacher_insert_exams on public.exams;
create policy teacher_insert_exams on public.exams
for insert to authenticated
with check (
  public.exam_guard_current_user_is_main_admin()
  or (
    public.exam_guard_current_user_is_admin()
    and owner_id = auth.uid()
  )
);

drop policy if exists teacher_update_exams on public.exams;
create policy teacher_update_exams on public.exams
for update to authenticated
using (
  public.exam_guard_current_user_is_main_admin()
  or (
    public.exam_guard_current_user_is_admin()
    and owner_id = auth.uid()
  )
)
with check (
  public.exam_guard_current_user_is_main_admin()
  or (
    public.exam_guard_current_user_is_admin()
    and owner_id = auth.uid()
  )
);

drop policy if exists teacher_delete_exams on public.exams;
create policy teacher_delete_exams on public.exams
for delete to authenticated
using (
  public.exam_guard_current_user_is_main_admin()
  or (
    public.exam_guard_current_user_is_admin()
    and owner_id = auth.uid()
  )
);

drop policy if exists admin_questions on public.questions;
create policy admin_questions on public.questions
for all to authenticated
using (public.exam_guard_can_access_exam(exam_id))
with check (public.exam_guard_can_access_exam(exam_id));

drop policy if exists admin_attempts on public.attempts;
create policy admin_attempts on public.attempts
for select to authenticated
using (public.exam_guard_can_access_exam(exam_id));

drop policy if exists admin_attempts_delete on public.attempts;
create policy admin_attempts_delete on public.attempts
for delete to authenticated
using (public.exam_guard_can_access_exam(exam_id));

drop policy if exists admin_responses on public.responses;
create policy admin_responses on public.responses
for select to authenticated
using (
  exists (
    select 1
    from public.attempts a
    where a.id = responses.attempt_id
      and public.exam_guard_can_access_exam(a.exam_id)
  )
);

drop policy if exists admin_events on public.proctor_events;
create policy admin_events on public.proctor_events
for select to authenticated
using (
  exists (
    select 1
    from public.attempts a
    where a.id = proctor_events.attempt_id
      and public.exam_guard_can_access_exam(a.exam_id)
  )
);

drop policy if exists own_exam_admin on public.exam_admins;
drop policy if exists main_admin_exam_admins on public.exam_admins;

create policy own_exam_admin on public.exam_admins
for select to authenticated
using (
  user_id = auth.uid()
  or public.exam_guard_current_user_is_main_admin()
);

create policy main_admin_exam_admins on public.exam_admins
for update to authenticated
using (public.exam_guard_current_user_is_main_admin())
with check (public.exam_guard_current_user_is_main_admin());

-- 5. Secure SECURITY DEFINER admin RPCs against cross-teacher access.
create or replace function public.admin_delete_attempt(p_attempt_id uuid)
returns boolean
language plpgsql
security definer
set search_path = public
as $admin$
declare
  v_deleted integer := 0;
begin
  if auth.uid() is null
     or not public.exam_guard_can_access_attempt(p_attempt_id) then
    raise exception 'You do not have access to this exam attempt.';
  end if;

  delete from public.attempts
  where id = p_attempt_id;

  get diagnostics v_deleted = row_count;
  return v_deleted = 1;
end;
$admin$;

create or replace function public.admin_delete_exam(p_exam_id uuid)
returns boolean
language plpgsql
security definer
set search_path = public
as $admin$
declare
  v_deleted integer := 0;
begin
  if auth.uid() is null
     or not public.exam_guard_can_access_exam(p_exam_id) then
    raise exception 'You do not have access to this examination.';
  end if;

  delete from public.exams
  where id = p_exam_id;

  get diagnostics v_deleted = row_count;
  return v_deleted = 1;
end;
$admin$;

create or replace function public.admin_get_attempt_report(p_attempt_id uuid)
returns jsonb
language plpgsql
security definer
set search_path = public
as $report$
declare
  v_report jsonb;
begin
  if auth.uid() is null
     or not public.exam_guard_can_access_attempt(p_attempt_id) then
    raise exception 'You do not have access to this exam attempt.';
  end if;

  v_report := public.exam_guard_build_attempt_report(p_attempt_id);
  if v_report is null then
    raise exception 'Only submitted attempts have result reports.';
  end if;

  return v_report;
end;
$report$;

-- 6. Helper for the Main Admin teacher switcher.
create or replace function public.get_teacher_workspaces()
returns table(
  user_id uuid,
  email text,
  display_name text,
  role text,
  is_admin boolean
)
language sql
stable
security definer
set search_path = public
as $teachers$
  select
    ea.user_id,
    ea.email,
    ea.display_name,
    ea.role,
    ea.is_admin
  from public.exam_admins ea
  where ea.is_admin = true
    and (
      ea.user_id = auth.uid()
      or public.exam_guard_current_user_is_main_admin()
    )
  order by
    case when ea.user_id = auth.uid() then 0 else 1 end,
    coalesce(ea.display_name, ea.email, ea.user_id::text);
$teachers$;

revoke all on function public.get_teacher_workspaces() from public;
grant execute on function public.get_teacher_workspaces() to authenticated;

-- Main Admin can authorize an existing Supabase Authentication user as a teacher.
create or replace function public.main_admin_add_teacher(
  p_email text,
  p_display_name text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public, auth
as $teachers$
declare
  v_user auth.users%rowtype;
begin
  if not public.exam_guard_current_user_is_main_admin() then
    raise exception 'Main Admin access required.';
  end if;

  select * into v_user
  from auth.users
  where lower(email) = lower(trim(p_email))
  limit 1;

  if not found then
    raise exception 'No Supabase Authentication user exists with that email. Create the user in Authentication > Users first.';
  end if;

  insert into public.exam_admins(user_id, email, display_name, role, is_admin)
  values (
    v_user.id,
    v_user.email,
    coalesce(nullif(trim(p_display_name),''), split_part(v_user.email,'@',1)),
    case when lower(v_user.email) = 'sir.princejobetroh@gmail.com' then 'main_admin' else 'teacher' end,
    true
  )
  on conflict (user_id) do update
  set email = excluded.email,
      display_name = coalesce(nullif(trim(p_display_name),''), public.exam_admins.display_name, excluded.display_name),
      role = case when lower(excluded.email) = 'sir.princejobetroh@gmail.com' then 'main_admin' else 'teacher' end,
      is_admin = true;

  return jsonb_build_object(
    'user_id', v_user.id,
    'email', v_user.email,
    'display_name', coalesce(nullif(trim(p_display_name),''), split_part(v_user.email,'@',1)),
    'enabled', true
  );
end;
$teachers$;

create or replace function public.main_admin_set_teacher_access(
  p_user_id uuid,
  p_enabled boolean
)
returns boolean
language plpgsql
security definer
set search_path = public
as $teachers$
declare
  v_email text;
begin
  if not public.exam_guard_current_user_is_main_admin() then
    raise exception 'Main Admin access required.';
  end if;

  select email into v_email
  from public.exam_admins
  where user_id = p_user_id;

  if lower(coalesce(v_email,'')) = 'sir.princejobetroh@gmail.com' then
    raise exception 'The Main Admin account cannot be disabled.';
  end if;

  update public.exam_admins
  set is_admin = coalesce(p_enabled,false),
      role = 'teacher'
  where user_id = p_user_id;

  return found;
end;
$teachers$;

revoke all on function public.main_admin_add_teacher(text,text) from public;
revoke all on function public.main_admin_set_teacher_access(uuid,boolean) from public;
grant execute on function public.main_admin_add_teacher(text,text) to authenticated;
grant execute on function public.main_admin_set_teacher_access(uuid,boolean) to authenticated;


grant select on public.exam_admins to authenticated;

-- Optional check after running:
-- select user_id, email, display_name, role, is_admin from public.exam_admins;
-- select id, code, title, owner_id from public.exams order by created_at desc;


-- ---------- Preserved proctor-photo evidence ----------
alter table public.proctor_photos
  add column if not exists evidence_saved boolean not null default false,
  add column if not exists evidence_saved_at timestamptz,
  add column if not exists evidence_saved_by uuid references auth.users(id) on delete set null;

create index if not exists proctor_photos_evidence_idx
  on public.proctor_photos(evidence_saved, captured_at);

create or replace function public.set_proctor_photo_evidence(
  p_photo_ids uuid[],
  p_saved boolean
)
returns integer
language plpgsql
security definer
set search_path = public
as $evidence$
declare
  v_count integer := 0;
begin
  if auth.uid() is null or not public.exam_guard_current_user_is_admin() then
    raise exception 'Teacher access required.';
  end if;

  update public.proctor_photos p
  set evidence_saved = coalesce(p_saved, false),
      evidence_saved_at = case when coalesce(p_saved, false) then now() else null end,
      evidence_saved_by = case when coalesce(p_saved, false) then auth.uid() else null end
  where p.id = any(p_photo_ids)
    and public.exam_guard_can_access_attempt(p.attempt_id);

  get diagnostics v_count = row_count;
  return v_count;
end;
$evidence$;

revoke all on function public.set_proctor_photo_evidence(uuid[],boolean) from public;
grant execute on function public.set_proctor_photo_evidence(uuid[],boolean) to authenticated;

-- Teacher recovery tools for accidental student submission.
-- Run once in Supabase SQL Editor.

create or replace function public.admin_reopen_attempt(p_attempt_id uuid)
returns boolean
language plpgsql
security definer
set search_path = public
as $reopen$
declare
  v_updated integer := 0;
begin
  if auth.uid() is null
     or not public.exam_guard_can_access_attempt(p_attempt_id) then
    raise exception 'You do not have access to this exam attempt.';
  end if;

  update public.attempts
  set status = 'active',
      submitted_at = null,
      score = null,
      max_score = null
  where id = p_attempt_id
    and status = 'submitted';

  get diagnostics v_updated = row_count;

  if v_updated = 1 then
    insert into public.proctor_events(attempt_id, event_type, details)
    values (
      p_attempt_id,
      'attempt_reopened_by_teacher',
      jsonb_build_object(
        'teacher_user_id', auth.uid(),
        'reopened_at', now()
      )
    );
  end if;

  return v_updated = 1;
end;
$reopen$;

create or replace function public.admin_reset_attempt(p_attempt_id uuid)
returns boolean
language plpgsql
security definer
set search_path = public
as $reset$
declare
  v_deleted integer := 0;
begin
  if auth.uid() is null
     or not public.exam_guard_can_access_attempt(p_attempt_id) then
    raise exception 'You do not have access to this exam attempt.';
  end if;

  -- Child records are also protected by ON DELETE CASCADE, but explicit
  -- deletion makes the reset behavior clear and removes saved work first.
  delete from public.responses where attempt_id = p_attempt_id;
  delete from public.proctor_events where attempt_id = p_attempt_id;
  delete from public.proctor_photos where attempt_id = p_attempt_id;

  delete from public.attempts
  where id = p_attempt_id;

  get diagnostics v_deleted = row_count;
  return v_deleted = 1;
end;
$reset$;

revoke all on function public.admin_reopen_attempt(uuid) from public;
revoke all on function public.admin_reset_attempt(uuid) from public;
grant execute on function public.admin_reopen_attempt(uuid) to authenticated;
grant execute on function public.admin_reset_attempt(uuid) to authenticated;

-- Exam-specific proctor access.
-- Run once in Supabase SQL Editor.
-- Proctors can view a published assigned exam and its attempts, and may Reset for Retake.
-- They cannot edit/draft/close/archive/delete the exam, edit questions, delete attempts,
-- or otherwise manage the exam.

create table if not exists public.exam_proctors (
  exam_id uuid not null references public.exams(id) on delete cascade,
  teacher_user_id uuid not null references auth.users(id) on delete cascade,
  assigned_by uuid references auth.users(id) on delete set null,
  assigned_at timestamptz not null default now(),
  primary key (exam_id, teacher_user_id)
);

create index if not exists exam_proctors_teacher_idx
  on public.exam_proctors(teacher_user_id, exam_id);

alter table public.exam_proctors enable row level security;

-- True only while the assigned exam is published and the teacher account is enabled.
create or replace function public.exam_guard_is_exam_proctor(p_exam_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $proctor$
  select exists(
    select 1
    from public.exam_proctors ep
    join public.exams e on e.id = ep.exam_id
    join public.exam_admins ea on ea.user_id = ep.teacher_user_id
    where ep.exam_id = p_exam_id
      and ep.teacher_user_id = auth.uid()
      and ea.is_admin = true
      and e.status = 'published'
      and coalesce(e.archived, false) = false
  );
$proctor$;

-- View access = owner/Main Admin OR published-exam proctor.
create or replace function public.exam_guard_can_view_exam(p_exam_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $view$
  select
    public.exam_guard_can_access_exam(p_exam_id)
    or public.exam_guard_is_exam_proctor(p_exam_id);
$view$;

create or replace function public.exam_guard_can_view_attempt(p_attempt_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $view$
  select exists(
    select 1
    from public.attempts a
    where a.id = p_attempt_id
      and public.exam_guard_can_view_exam(a.exam_id)
  );
$view$;

-- Assignment rows can be seen by Main Admin, the exam owner, or the assigned proctor.
drop policy if exists exam_proctors_select on public.exam_proctors;
create policy exam_proctors_select
on public.exam_proctors
for select to authenticated
using (
  teacher_user_id = auth.uid()
  or public.exam_guard_current_user_is_main_admin()
  or exists(
    select 1
    from public.exams e
    where e.id = exam_proctors.exam_id
      and e.owner_id = auth.uid()
      and public.exam_guard_current_user_is_admin()
  )
);

-- Assignment mutations are intentionally RPC-only.
revoke insert, update, delete on public.exam_proctors from authenticated;
grant select on public.exam_proctors to authenticated;

create or replace function public.get_proctor_candidates()
returns table(
  user_id uuid,
  email text,
  display_name text
)
language sql
stable
security definer
set search_path = public
as $proctor$
  select ea.user_id, ea.email, ea.display_name
  from public.exam_admins ea
  where public.exam_guard_current_user_is_admin()
    and ea.is_admin = true
    and ea.user_id <> auth.uid()
  order by coalesce(nullif(ea.display_name,''), ea.email), ea.email;
$proctor$;

create or replace function public.get_exam_proctor_assignments(p_exam_id uuid default null)
returns table(
  exam_id uuid,
  exam_title text,
  exam_code text,
  teacher_user_id uuid,
  teacher_email text,
  teacher_name text,
  assigned_at timestamptz
)
language sql
stable
security definer
set search_path = public
as $proctor$
  select
    e.id,
    e.title,
    e.code,
    ep.teacher_user_id,
    ea.email,
    ea.display_name,
    ep.assigned_at
  from public.exam_proctors ep
  join public.exams e on e.id = ep.exam_id
  left join public.exam_admins ea on ea.user_id = ep.teacher_user_id
  where (p_exam_id is null or e.id = p_exam_id)
    and (
      public.exam_guard_current_user_is_main_admin()
      or (
        public.exam_guard_current_user_is_admin()
        and e.owner_id = auth.uid()
      )
      or ep.teacher_user_id = auth.uid()
    )
  order by e.created_at desc, coalesce(nullif(ea.display_name,''), ea.email);
$proctor$;

create or replace function public.assign_exam_proctor(
  p_exam_id uuid,
  p_teacher_user_id uuid
)
returns boolean
language plpgsql
security definer
set search_path = public
as $proctor$
declare
  v_exam public.exams%rowtype;
begin
  if auth.uid() is null or not public.exam_guard_current_user_is_admin() then
    raise exception 'Teacher access required.';
  end if;

  select * into v_exam from public.exams where id = p_exam_id;
  if not found then raise exception 'Exam not found.'; end if;

  if not (
    public.exam_guard_current_user_is_main_admin()
    or v_exam.owner_id = auth.uid()
  ) then
    raise exception 'Only the exam owner or Main Admin can assign a proctor.';
  end if;

  if v_exam.status <> 'published' or coalesce(v_exam.archived, false) then
    raise exception 'Proctors can only be assigned to a published examination.';
  end if;

  if p_teacher_user_id = v_exam.owner_id then
    raise exception 'The exam owner does not need a proctor assignment.';
  end if;

  if not exists(
    select 1 from public.exam_admins
    where user_id = p_teacher_user_id and is_admin = true
  ) then
    raise exception 'Select an authorized teacher.';
  end if;

  insert into public.exam_proctors(exam_id, teacher_user_id, assigned_by)
  values(p_exam_id, p_teacher_user_id, auth.uid())
  on conflict(exam_id, teacher_user_id)
  do update set assigned_by = excluded.assigned_by, assigned_at = now();

  return true;
end;
$proctor$;

create or replace function public.remove_exam_proctor(
  p_exam_id uuid,
  p_teacher_user_id uuid
)
returns boolean
language plpgsql
security definer
set search_path = public
as $proctor$
declare
  v_owner uuid;
  v_deleted integer := 0;
begin
  select owner_id into v_owner from public.exams where id = p_exam_id;
  if v_owner is null then raise exception 'Exam not found.'; end if;

  if not (
    public.exam_guard_current_user_is_main_admin()
    or (public.exam_guard_current_user_is_admin() and v_owner = auth.uid())
  ) then
    raise exception 'Only the exam owner or Main Admin can remove a proctor.';
  end if;

  delete from public.exam_proctors
  where exam_id = p_exam_id
    and teacher_user_id = p_teacher_user_id;

  get diagnostics v_deleted = row_count;
  return v_deleted = 1;
end;
$proctor$;

revoke all on function public.get_proctor_candidates() from public;
revoke all on function public.get_exam_proctor_assignments(uuid) from public;
revoke all on function public.assign_exam_proctor(uuid,uuid) from public;
revoke all on function public.remove_exam_proctor(uuid,uuid) from public;
grant execute on function public.get_proctor_candidates() to authenticated;
grant execute on function public.get_exam_proctor_assignments(uuid) to authenticated;
grant execute on function public.assign_exam_proctor(uuid,uuid) to authenticated;
grant execute on function public.remove_exam_proctor(uuid,uuid) to authenticated;

-- Exams: published proctored exams are visible, but only owners/Main Admin retain write policies.
drop policy if exists admin_exams on public.exams;
create policy admin_exams on public.exams
for select to authenticated
using (public.exam_guard_can_view_exam(id));

-- Questions: keep owner/Main Admin management, add read-only proctor access.
drop policy if exists admin_questions on public.questions;
create policy admin_questions on public.questions
for all to authenticated
using (public.exam_guard_can_access_exam(exam_id))
with check (public.exam_guard_can_access_exam(exam_id));

drop policy if exists proctor_questions_select on public.questions;
create policy proctor_questions_select on public.questions
for select to authenticated
using (public.exam_guard_can_view_exam(exam_id));

-- Attempts: proctors may read, but direct deletion remains owner/Main Admin only.
drop policy if exists admin_attempts on public.attempts;
create policy admin_attempts on public.attempts
for select to authenticated
using (public.exam_guard_can_view_exam(exam_id));

drop policy if exists admin_attempts_delete on public.attempts;
create policy admin_attempts_delete on public.attempts
for delete to authenticated
using (public.exam_guard_can_access_exam(exam_id));

-- Saved responses and proctoring events are read-only for proctors.
drop policy if exists admin_responses on public.responses;
create policy admin_responses on public.responses
for select to authenticated
using (
  exists (
    select 1 from public.attempts a
    where a.id = responses.attempt_id
      and public.exam_guard_can_view_exam(a.exam_id)
  )
);

drop policy if exists admin_events on public.proctor_events;
create policy admin_events on public.proctor_events
for select to authenticated
using (
  exists (
    select 1 from public.attempts a
    where a.id = proctor_events.attempt_id
      and public.exam_guard_can_view_exam(a.exam_id)
  )
);

drop policy if exists teacher_proctor_photos_select on public.proctor_photos;
create policy teacher_proctor_photos_select
on public.proctor_photos
for select to authenticated
using (public.exam_guard_can_view_attempt(attempt_id));

-- Attempt reports are viewable by proctors of a currently published assigned exam.
create or replace function public.admin_get_attempt_report(p_attempt_id uuid)
returns jsonb
language plpgsql
security definer
set search_path = public
as $report$
declare
  v_report jsonb;
begin
  if auth.uid() is null or not public.exam_guard_can_view_attempt(p_attempt_id) then
    raise exception 'You do not have access to this exam attempt.';
  end if;

  v_report := public.exam_guard_build_attempt_report(p_attempt_id);

  if v_report is null then
    raise exception 'Only submitted attempts have result reports.';
  end if;

  return v_report;
end;
$report$;

-- Reopen remains owner/Main Admin only.
create or replace function public.admin_reopen_attempt(p_attempt_id uuid)
returns boolean
language plpgsql
security definer
set search_path = public
as $reopen$
declare
  v_updated integer := 0;
begin
  if auth.uid() is null
     or not public.exam_guard_can_access_attempt(p_attempt_id) then
    raise exception 'Only the exam owner or Main Admin can reopen this attempt.';
  end if;

  update public.attempts
  set status = 'active',
      submitted_at = null,
      score = null,
      max_score = null
  where id = p_attempt_id
    and status = 'submitted';

  get diagnostics v_updated = row_count;

  if v_updated = 1 then
    insert into public.proctor_events(attempt_id, event_type, details)
    values (
      p_attempt_id,
      'attempt_reopened_by_teacher',
      jsonb_build_object('teacher_user_id', auth.uid(), 'reopened_at', now())
    );
  end if;

  return v_updated = 1;
end;
$reopen$;

-- Reset for Retake is the one recovery action explicitly allowed to a proctor.
create or replace function public.admin_reset_attempt(p_attempt_id uuid)
returns boolean
language plpgsql
security definer
set search_path = public
as $reset$
declare
  v_deleted integer := 0;
begin
  if auth.uid() is null
     or not public.exam_guard_can_view_attempt(p_attempt_id) then
    raise exception 'You do not have access to reset this exam attempt.';
  end if;

  delete from public.responses where attempt_id = p_attempt_id;
  delete from public.proctor_events where attempt_id = p_attempt_id;
  delete from public.proctor_photos where attempt_id = p_attempt_id;

  delete from public.attempts where id = p_attempt_id;

  get diagnostics v_deleted = row_count;
  return v_deleted = 1;
end;
$reset$;

-- Mathematics display, Binary Response, and criteria-based Essay questions.
-- Run once in Supabase SQL Editor.

alter table public.questions
  add column if not exists rubric_criteria jsonb not null default '[]'::jsonb;

alter table public.questions
  drop constraint if exists questions_question_type_check;

alter table public.questions
  add constraint questions_question_type_check
  check (question_type in ('mcq','binary','text','essay'));

-- Return rubric metadata with active exam questions. Students still do not receive
-- answer keys through this RPC.
drop function if exists public.get_exam_questions(uuid);

create function public.get_exam_questions(p_attempt_token uuid)
returns table(
  question_id uuid,
  "position" integer,
  prompt text,
  question_type text,
  choices jsonb,
  points numeric,
  rubric_criteria jsonb
)
language plpgsql
security definer
set search_path = public
as $questions$
declare
  v_attempt public.attempts%rowtype;
  v_exam public.exams%rowtype;
begin
  select * into v_attempt
  from public.attempts
  where attempt_token = p_attempt_token;

  if not found or v_attempt.status <> 'active' then
    raise exception 'Invalid or inactive exam attempt.';
  end if;

  select * into v_exam
  from public.exams
  where id = v_attempt.exam_id;

  if now() > v_attempt.started_at + make_interval(mins => v_exam.duration_minutes) then
    update public.attempts
    set status = 'expired'
    where id = v_attempt.id;
    raise exception 'Exam time has expired.';
  end if;

  return query
  select
    q.id,
    q.position as "position",
    q.prompt,
    q.question_type,
    q.choices,
    q.points,
    q.rubric_criteria
  from public.questions q
  where q.exam_id = v_attempt.exam_id
  order by q.position;
end;
$questions$;

revoke all on function public.get_exam_questions(uuid) from public;
grant execute on function public.get_exam_questions(uuid) to anon, authenticated;


-- Rubric type for essay questions.
alter table public.questions
  add column if not exists rubric_type text not null default 'analytic';

alter table public.questions
  drop constraint if exists questions_rubric_type_check;

alter table public.questions
  add constraint questions_rubric_type_check
  check (rubric_type in ('analytic','holistic'));

drop function if exists public.get_exam_questions(uuid);

create function public.get_exam_questions(p_attempt_token uuid)
returns table(
  question_id uuid,
  "position" integer,
  prompt text,
  question_type text,
  choices jsonb,
  points numeric,
  rubric_type text,
  rubric_criteria jsonb
)
language plpgsql
security definer
set search_path = public
as $questions$
declare
  v_attempt public.attempts%rowtype;
  v_exam public.exams%rowtype;
begin
  select * into v_attempt
  from public.attempts
  where attempt_token = p_attempt_token;

  if not found or v_attempt.status <> 'active' then
    raise exception 'Invalid or inactive exam attempt.';
  end if;

  select * into v_exam
  from public.exams
  where id = v_attempt.exam_id;

  if now() > v_attempt.started_at + make_interval(mins => v_exam.duration_minutes) then
    update public.attempts set status = 'expired' where id = v_attempt.id;
    raise exception 'Exam time has expired.';
  end if;

  return query
  select
    q.id,
    q.position as "position",
    q.prompt,
    q.question_type,
    q.choices,
    q.points,
    q.rubric_type,
    q.rubric_criteria
  from public.questions q
  where q.exam_id = v_attempt.exam_id
  order by q.position;
end;
$questions$;

revoke all on function public.get_exam_questions(uuid) from public;
grant execute on function public.get_exam_questions(uuid) to anon, authenticated;

-- Constructed-response grading, short response, math solver, and exam sections.
-- Run once in Supabase SQL Editor.

alter table public.questions
  add column if not exists section_title text not null default 'Part 1';

alter table public.questions
  drop constraint if exists questions_question_type_check;

alter table public.questions
  add constraint questions_question_type_check
  check (question_type in ('mcq','binary','text','essay','short_response','math_solver'));

alter table public.responses
  add column if not exists provisional_score numeric(10,2),
  add column if not exists provisional_reason text,
  add column if not exists teacher_score numeric(10,2),
  add column if not exists teacher_comment text,
  add column if not exists review_status text not null default 'not_required',
  add column if not exists reviewed_at timestamptz,
  add column if not exists reviewed_by uuid references auth.users(id) on delete set null;

alter table public.responses
  drop constraint if exists responses_review_status_check;

alter table public.responses
  add constraint responses_review_status_check
  check (review_status in ('not_required','pending','approved'));

alter table public.attempts
  add column if not exists grading_status text not null default 'not_required',
  add column if not exists provisional_score numeric(10,2),
  add column if not exists provisional_max_score numeric(10,2),
  add column if not exists grading_approved_at timestamptz,
  add column if not exists grading_approved_by uuid references auth.users(id) on delete set null;

alter table public.attempts
  drop constraint if exists attempts_grading_status_check;

alter table public.attempts
  add constraint attempts_grading_status_check
  check (grading_status in ('not_required','pending_ai','pending_review','approved'));

drop function if exists public.get_exam_questions(uuid);

create function public.get_exam_questions(p_attempt_token uuid)
returns table(
  question_id uuid,
  "position" integer,
  section_title text,
  prompt text,
  question_type text,
  choices jsonb,
  points numeric,
  rubric_type text,
  rubric_criteria jsonb
)
language plpgsql
security definer
set search_path = public
as $questions$
declare
  v_attempt public.attempts%rowtype;
  v_exam public.exams%rowtype;
begin
  select * into v_attempt
  from public.attempts
  where attempt_token = p_attempt_token;

  if not found or v_attempt.status <> 'active' then
    raise exception 'Invalid or inactive exam attempt.';
  end if;

  select * into v_exam from public.exams where id = v_attempt.exam_id;

  if now() > v_attempt.started_at + make_interval(mins => v_exam.duration_minutes) then
    update public.attempts set status = 'expired' where id = v_attempt.id;
    raise exception 'Exam time has expired.';
  end if;

  return query
  select
    q.id,
    q.position as "position",
    q.section_title,
    q.prompt,
    q.question_type,
    q.choices,
    q.points,
    q.rubric_type,
    q.rubric_criteria
  from public.questions q
  where q.exam_id = v_attempt.exam_id
  order by q.position;
end;
$questions$;

create or replace function public.submit_exam(p_attempt_token uuid)
returns table(score numeric, max_score numeric)
language plpgsql
security definer
set search_path = public
as $submit$
declare
  v_attempt public.attempts%rowtype;
  v_score numeric;
  v_auto_max numeric;
  v_has_constructed boolean;
begin
  select * into v_attempt from public.attempts where attempt_token = p_attempt_token;

  if not found then raise exception 'Invalid exam attempt.'; end if;

  if v_attempt.status = 'submitted' then
    return query select v_attempt.score, v_attempt.max_score;
    return;
  end if;

  select
    coalesce(sum(
      case
        when q.question_type in ('mcq','binary')
         and q.correct_answer is not null
         and lower(trim(coalesce(r.answer,''))) = lower(trim(q.correct_answer))
        then q.points else 0
      end
    ),0),
    coalesce(sum(case when q.question_type in ('mcq','binary') then q.points else 0 end),0),
    bool_or(q.question_type in ('essay','short_response','math_solver'))
  into v_score, v_auto_max, v_has_constructed
  from public.questions q
  left join public.responses r on r.question_id = q.id and r.attempt_id = v_attempt.id
  where q.exam_id = v_attempt.exam_id;

  update public.responses r
  set review_status = 'pending'
  from public.questions q
  where r.question_id = q.id
    and r.attempt_id = v_attempt.id
    and q.question_type in ('essay','short_response','math_solver');

  update public.attempts
  set status = 'submitted',
      submitted_at = now(),
      score = v_score,
      max_score = v_auto_max,
      grading_status = case when coalesce(v_has_constructed,false) then 'pending_ai' else 'approved' end,
      provisional_score = null,
      provisional_max_score = null
  where id = v_attempt.id;

  insert into public.proctor_events(attempt_id,event_type,details)
  values(v_attempt.id,'exam_submitted',jsonb_build_object('auto_score',v_score,'auto_max_score',v_auto_max,'constructed_review_required',coalesce(v_has_constructed,false)));

  return query select v_score, v_auto_max;
end;
$submit$;

create or replace function public.admin_get_grading_review(p_attempt_id uuid)
returns jsonb
language sql
stable
security definer
set search_path = public
as $review$
  select jsonb_build_object(
    'attempt_id', a.id,
    'student_name', s.full_name,
    'student_no', s.student_no,
    'exam_title', e.title,
    'grading_status', a.grading_status,
    'current_score', a.score,
    'current_max_score', a.max_score,
    'provisional_score', a.provisional_score,
    'provisional_max_score', a.provisional_max_score,
    'items', coalesce((
      select jsonb_agg(
        jsonb_build_object(
          'question_id', q.id,
          'position', q.position,
          'section_title', q.section_title,
          'prompt', q.prompt,
          'question_type', q.question_type,
          'points', q.points,
          'reference_answer', q.correct_answer,
          'rubric_type', q.rubric_type,
          'rubric_criteria', q.rubric_criteria,
          'student_answer', coalesce(r.answer,''),
          'provisional_score', r.provisional_score,
          'provisional_reason', r.provisional_reason,
          'teacher_score', r.teacher_score,
          'teacher_comment', r.teacher_comment,
          'review_status', r.review_status
        ) order by q.position
      )
      from public.questions q
      left join public.responses r on r.question_id=q.id and r.attempt_id=a.id
      where q.exam_id=a.exam_id
        and q.question_type in ('essay','short_response','math_solver')
    ), '[]'::jsonb)
  )
  from public.attempts a
  join public.students s on s.id=a.student_id
  join public.exams e on e.id=a.exam_id
  where a.id=p_attempt_id
    and a.status='submitted'
    and public.exam_guard_can_access_attempt(a.id);
$review$;

create or replace function public.admin_approve_constructed_scores(
  p_attempt_id uuid,
  p_scores jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $approve$
declare
  v_item jsonb;
  v_question_id uuid;
  v_score numeric;
  v_comment text;
  v_auto_score numeric := 0;
  v_auto_max numeric := 0;
  v_constructed_score numeric := 0;
  v_constructed_max numeric := 0;
  v_total_score numeric := 0;
  v_total_max numeric := 0;
begin
  if auth.uid() is null or not public.exam_guard_can_access_attempt(p_attempt_id) then
    raise exception 'Only the exam owner or Main Admin can approve constructed-response scores.';
  end if;

  if jsonb_typeof(p_scores) <> 'array' then
    raise exception 'Scores must be supplied as an array.';
  end if;

  for v_item in select * from jsonb_array_elements(p_scores)
  loop
    v_question_id := (v_item->>'question_id')::uuid;
    v_score := (v_item->>'score')::numeric;
    v_comment := nullif(trim(coalesce(v_item->>'comment','')),'');

    if not exists(
      select 1 from public.questions q
      join public.attempts a on a.exam_id=q.exam_id
      where a.id=p_attempt_id
        and q.id=v_question_id
        and q.question_type in ('essay','short_response','math_solver')
        and v_score between 0 and q.points
    ) then
      raise exception 'Invalid score for question %.', v_question_id;
    end if;

    update public.responses
    set teacher_score=v_score,
        teacher_comment=v_comment,
        review_status='approved',
        reviewed_at=now(),
        reviewed_by=auth.uid()
    where attempt_id=p_attempt_id and question_id=v_question_id;
  end loop;

  select
    coalesce(sum(case when q.question_type in ('mcq','binary')
      and q.correct_answer is not null
      and lower(trim(coalesce(r.answer,'')))=lower(trim(q.correct_answer))
      then q.points else 0 end),0),
    coalesce(sum(case when q.question_type in ('mcq','binary') then q.points else 0 end),0),
    coalesce(sum(case when q.question_type in ('essay','short_response','math_solver') then coalesce(r.teacher_score,0) else 0 end),0),
    coalesce(sum(case when q.question_type in ('essay','short_response','math_solver') then q.points else 0 end),0)
  into v_auto_score,v_auto_max,v_constructed_score,v_constructed_max
  from public.questions q
  left join public.responses r on r.question_id=q.id and r.attempt_id=p_attempt_id
  join public.attempts a on a.exam_id=q.exam_id
  where a.id=p_attempt_id;

  v_total_score := v_auto_score + v_constructed_score;
  v_total_max := v_auto_max + v_constructed_max;

  update public.attempts
  set score=v_total_score,
      max_score=v_total_max,
      grading_status='approved',
      grading_approved_at=now(),
      grading_approved_by=auth.uid()
  where id=p_attempt_id;

  return jsonb_build_object('score',v_total_score,'max_score',v_total_max,'grading_status','approved');
end;
$approve$;

revoke all on function public.admin_get_grading_review(uuid) from public;
revoke all on function public.admin_approve_constructed_scores(uuid,jsonb) from public;
grant execute on function public.admin_get_grading_review(uuid) to authenticated;
grant execute on function public.admin_approve_constructed_scores(uuid,jsonb) to authenticated;

